---
stages:
  - build

rpm-build:
  stage: build
  image: centos:7
  before_script:
    - yum -y install
        epel-release
        git
        rpm-build
        rpmdevtools
  script:
    - mkdir -p rpmbuild/{SOURCES,RPMS,SRPMS}
    - spectool -g -C rpmbuild/SOURCES build/bouncer.spec
    - rpmbuild --define "_topdir `pwd`" -bb build/bouncer.spec
  artifacts:
    paths:
      - "*.rpm"