---
stages:
  - build

#rpm-build:
#  stage: build
#  image: centos:7
#  before_script:
#    - yum -y install
#        epel-release
#        git
#        rpm-build
#        rpmdevtools
#        make
#  script:
#    - mkdir -p rpmbuild/{SOURCES,RPMS,SRPMS}
#    - spectool -g -C rpmbuild/SOURCES build/bouncer.spec
#    - rpmbuild --define "_topdir `pwd`/rpmbuild" -bb build/bouncer.spec
#  artifacts:
#    paths:
#      - "*.rpm"
variables:
  OS: linux
  ARCH: amd64
  VERSION: 0.0.1
  GOPATH: ${CI_ROJECT_DIR}/dist

build-go:
  stage: build
  image: golang:1.14.3-alpine
  before_script:
    - go mod vendor
  script:
    - OS=${OS} ARCH=${ARCH} build/build.sh
  after_script:
    - ls -la ${GOPATH}
    - ls -la ${GOPATH}/bin/
  artifacts:
    paths:
      - ${GOPATH}/bin/${OS}_${ARCH}/bouncer
