---
stages:
  - build
  - build-rpm

#rpm-build:
#  stage: build
#  image: centos:7
#  before_script:
#    - yum -y install
#        epel-release
#        git
#        rpm-build
#        rpmdevtools
#        make
#  script:
#    - mkdir -p rpmbuild/{SOURCES,RPMS,SRPMS}
#    - spectool -g -C rpmbuild/SOURCES build/bouncer.spec
#    - rpmbuild --define "_topdir `pwd`/rpmbuild" -bb build/bouncer.spec
#  artifacts:
#    paths:
#      - "*.rpm"
variables:
  OS: linux
  ARCH: amd64
  VERSION: 0.0.1
  DISTPATH: dist
  GOPATH: ${CI_PROJECT_DIR}/${DISTPATH}

build-go:
  stage: build
  image: golang:1.14.3-alpine
  before_script:
    - go mod vendor
  script:
    - build/build.sh
  after_script:
    - cp config/bouncer.config.example ${GOPATH}/bin/bouncer.yaml
  artifacts:
    paths:
      - ${DISTPATH}/bin/

build-rpm:
  stage: build-rpm
  image: perconalab/rpmbuild:latest
  before_script:
    - ls -la %{DISTPATH}
    - ls -la .
    - cp -R %{DISTPATH}/bin/* SOURCES/
  script:
    - rpmbuild -bb build/bouncer.spec
