---
stages:
  - build

rpm-build:
  stage: build
  image: centos:7
  before_script:
    - yum -y install
        epel-release
        git
        rpm-build
        rpmdevtools
  script:
    - mkdir -p rpmbuild/{SOURCES, RPMS}
    - cd rpmbuild/SOURCES; spectool -g build/bouncer.spec
    - rpmbuild -bp build/bouncer.spec
  artifacts:
    paths:
      - "*.rpm"